export const user =[
    {
        id: 1,
        name: {
            firstname: "Sheilo ",
            lastname: "Saraga",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "sheil",
        password: "Saraga123",
    },
    {
        id: 2,
        name: {
            firstname: "Jesriel",
            lastname: "Pilipino",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "jesriel",
        password: "Pilipino123",
    },
    {
        id: 3,
        name: {
            firstname: "Kathrine",
            lastname: "Ayuban",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "kath2",
        password: "Kath123",
    },
    {
        id: 4,
        name: {
            firstname: "Fermo ",
            lastname: "Asufra",
        },
        course: "",
        year: '',
        section: "",
        userType: "Teacher",
        username: "FG",
        password: "Asufra123",
    },
    {
        id: 5,
        name: {
            firstname: "Winzeal",
            lastname: "Agoc",
        },
        course: "",
        year: "",
        section: "",
        userType: "Teaher",
        username: "Winz",
        password: "Agoc123",
    },
    {
        id: 6,
        name: {
            firstname: "Catherine Leah",
            lastname: "Gabo",
        },
        course: "",
        year: '',
        section: "",
        userType: "Teacher",
        username: "@cathleah",
        password: "Gabo123",
    },
    {
        id: 7,
        name: {
            firstname: "Jerry",
            lastname: "Ale",
        },
        course: "",
        year: '',
        section: "",
        userType: "Teacher",
        username: "Jerry",
        password: "Ale123",
    },
    {
        id: 8,
        name: {
            firstname: "James",
            lastname: "Bucia",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "warren",
        password: "Bucia123",
    },
    {
        id: 9,
        name: {
            firstname: "Airen",
            lastname: "Bongcaras",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "Pipay",
        password: "Bongcaras123",
    },
    {
        id: 10,
        name: {
            firstname: "Ria Mae",
            lastname: "Angcahan",
        },
        course: "BS Information Technology",
        year: 3,
        section: "A",
        userType: "Student",
        username: "Yang2",
        password: "Angcahan123",
    },
];